package vu.lt.mybatis.model;

public class PlayerGame {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_GAME.PLAYERS_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    private Integer playersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER_GAME.GAMES_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    private Integer gamesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_GAME.PLAYERS_ID
     *
     * @return the value of PUBLIC.PLAYER_GAME.PLAYERS_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    public Integer getPlayersId() {
        return playersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_GAME.PLAYERS_ID
     *
     * @param playersId the value for PUBLIC.PLAYER_GAME.PLAYERS_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    public void setPlayersId(Integer playersId) {
        this.playersId = playersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER_GAME.GAMES_ID
     *
     * @return the value of PUBLIC.PLAYER_GAME.GAMES_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    public Integer getGamesId() {
        return gamesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER_GAME.GAMES_ID
     *
     * @param gamesId the value for PUBLIC.PLAYER_GAME.GAMES_ID
     *

     * @mbg.generated Sun Mar 31 20:54:03 EEST 2019

     */
    public void setGamesId(Integer gamesId) {
        this.gamesId = gamesId;
    }
}